SET PATH_TO_BUILD_DIRECTORY=%~d0%~p0

SET PATH_TO_FAKE_DIRECTORY=%PATH_TO_BUILD_DIRECTORY%.fake

SET PATH_TO_FAKE_EXE=%PATH_TO_FAKE_DIRECTORY%\fake.exe

IF NOT EXIST "%PATH_TO_FAKE_EXE%" (
  dotnet tool install fake-cli --tool-path %PATH_TO_FAKE_DIRECTORY% --version 5.*
)

@REM %PATH_TO_FAKE_EXE% -v run %PATH_TO_BUILD_DIRECTORY%fake.fsx %*
%PATH_TO_FAKE_EXE% -s run %PATH_TO_BUILD_DIRECTORY%fake.fsx %*